# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - AdeemyAnalytics

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './artifact/release.zip' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)

permissions:
  id-token: write  # Requerido para OIDC
  contents: read  # Permisos adicionales de lectura

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5 
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          
      # Nuevo paso para verificar las dependencias
      - name: Install dependencies
        run: pip install -r requirements.txt
        env:
          pythonLocation: ${{ env.pythonLocation }}

      # Opcional: Añadir paso para ejecutar tests

      - name: Zip artifact for deployment
        run: zip -r release.zip ./* -x '.venv/*' '.git/*' '.github/*'

      - name: List ZIP contents
        run: unzip -l release.zip

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: ./artifact  # Especificamos un directorio para el artefactos

      - name: Login to Azure using OpenID Connect (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_50AF5B3A82A94604806AB2305D2E82CD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_9D498C747F2E4CB7A0D4AFD2D376F9B2 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4A651FBA222542D9A4C1191AD053BBAF }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'AdeemyFunctionsApp'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
          
      - name: Clean up artifacts (optional)
        run: rm -f release.zip        